import { PrismaClient } from '@prisma/client';

export async function seedMaintenanceTemplates(
  prisma: PrismaClient
): Promise<void> {
  console.log(
    '\n   [MANT] Seeding MaintenanceTemplates globales por tipo de vehículo...'
  );

  const baseItems = await prisma.mantItem.findMany({
    where: { isGlobal: true },
  });

  const resolveItem = (name: string): string => {
    const item = baseItems.find(i => i.name === name);
    if (!item) {
      console.warn(`      ⚠️  Item KB no encontrado: "${name}"`);
      return '';
    }
    return item.id;
  };

  // ─────────────────────────────────────────────────────────────────────────
  // KIT A — LIGERO (Automóvil / Campero / SUV)
  // Ritmo: 5K MENOR → 10K MAYOR → repeating
  // ─────────────────────────────────────────────────────────────────────────
  const getBasicPackages = () => [
    {
      name: 'Servicio Menor — 5,000 km',
      triggerKm: 5000,
      estimatedCost: 180000,
      estimatedTime: 1.5,
      priority: 'MEDIUM' as const,
      items: [
        {
          name: 'Cambio aceite motor',
          triggerKm: 5000,
          estimatedTime: 0.5,
          order: 1,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aceite',
          triggerKm: 5000,
          estimatedTime: 0.2,
          order: 2,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspección general frenos',
          triggerKm: 5000,
          estimatedTime: 0.3,
          order: 3,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspeccion baterias',
          triggerKm: 5000,
          estimatedTime: 0.2,
          order: 4,
          priority: 'LOW' as const,
        },
        {
          name: 'Verificación presión',
          triggerKm: 5000,
          estimatedTime: 0.2,
          order: 5,
          priority: 'MEDIUM' as const,
        },
      ],
    },
    {
      name: 'Servicio Mayor — 10,000 km',
      triggerKm: 10000,
      estimatedCost: 320000,
      estimatedTime: 2.5,
      priority: 'HIGH' as const,
      items: [
        {
          name: 'Cambio aceite motor',
          triggerKm: 10000,
          estimatedTime: 0.5,
          order: 1,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aceite',
          triggerKm: 10000,
          estimatedTime: 0.2,
          order: 2,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aire',
          triggerKm: 10000,
          estimatedTime: 0.2,
          order: 3,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Cambio filtro combustible',
          triggerKm: 10000,
          estimatedTime: 0.3,
          order: 4,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspección general frenos',
          triggerKm: 10000,
          estimatedTime: 0.4,
          order: 5,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspección suspensión',
          triggerKm: 10000,
          estimatedTime: 0.3,
          order: 6,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Rotación neumáticos',
          triggerKm: 10000,
          estimatedTime: 0.5,
          order: 7,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion baterias',
          triggerKm: 10000,
          estimatedTime: 0.2,
          order: 8,
          priority: 'LOW' as const,
        },
        {
          name: 'Limpieza terminales batería',
          triggerKm: 10000,
          estimatedTime: 0.2,
          order: 9,
          priority: 'LOW' as const,
        },
      ],
    },
    {
      name: 'Servicio Mayor + — 20,000 km',
      triggerKm: 20000,
      estimatedCost: 480000,
      estimatedTime: 3.5,
      priority: 'HIGH' as const,
      items: [
        {
          name: 'Cambio aceite motor',
          triggerKm: 20000,
          estimatedTime: 0.5,
          order: 1,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aceite',
          triggerKm: 20000,
          estimatedTime: 0.2,
          order: 2,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aire',
          triggerKm: 20000,
          estimatedTime: 0.2,
          order: 3,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Cambio filtro combustible',
          triggerKm: 20000,
          estimatedTime: 0.3,
          order: 4,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspección general frenos',
          triggerKm: 20000,
          estimatedTime: 0.5,
          order: 5,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio líquido freno',
          triggerKm: 20000,
          estimatedTime: 0.4,
          order: 6,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspección suspensión',
          triggerKm: 20000,
          estimatedTime: 0.4,
          order: 7,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Engrase suspensión',
          triggerKm: 20000,
          estimatedTime: 0.3,
          order: 8,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Cambio aceite transmisión',
          triggerKm: 20000,
          estimatedTime: 0.8,
          order: 9,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Rotación neumáticos',
          triggerKm: 20000,
          estimatedTime: 0.5,
          order: 10,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Balanceo ruedas',
          triggerKm: 20000,
          estimatedTime: 0.7,
          order: 11,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Limpieza terminales batería',
          triggerKm: 20000,
          estimatedTime: 0.2,
          order: 12,
          priority: 'LOW' as const,
        },
      ],
    },
  ];

  // ─────────────────────────────────────────────────────────────────────────
  // KIT B — PICKUP / CAMIONETA (Hilux / Ranger / Furgón)
  // Ritmo: 5K MENOR → 10K MAYOR → 20K MAYOR+ → 40K MAYOR++
  // ─────────────────────────────────────────────────────────────────────────
  const getPickupPackages = () => [
    {
      name: 'Mantenimiento Menor — 5,000 km',
      triggerKm: 5000,
      estimatedCost: 350000,
      estimatedTime: 2.0,
      priority: 'MEDIUM' as const,
      items: [
        {
          name: 'Cambio aceite motor',
          triggerKm: 5000,
          estimatedTime: 0.5,
          order: 1,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aceite',
          triggerKm: 5000,
          estimatedTime: 0.3,
          order: 2,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspección general frenos',
          triggerKm: 5000,
          estimatedTime: 0.3,
          order: 3,
          priority: 'HIGH' as const,
        },
        {
          name: 'Engrase suspensión',
          triggerKm: 5000,
          estimatedTime: 0.3,
          order: 4,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Rotación neumáticos',
          triggerKm: 5000,
          estimatedTime: 0.5,
          order: 5,
          priority: 'MEDIUM' as const,
        },
      ],
    },
    {
      name: 'Mantenimiento Mayor — 10,000 km',
      triggerKm: 10000,
      estimatedCost: 620000,
      estimatedTime: 3.5,
      priority: 'HIGH' as const,
      items: [
        {
          name: 'Cambio aceite motor',
          triggerKm: 10000,
          estimatedTime: 0.5,
          order: 1,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aceite',
          triggerKm: 10000,
          estimatedTime: 0.3,
          order: 2,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aire',
          triggerKm: 10000,
          estimatedTime: 0.2,
          order: 3,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Cambio filtro combustible',
          triggerKm: 10000,
          estimatedTime: 0.3,
          order: 4,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspección general frenos',
          triggerKm: 10000,
          estimatedTime: 0.4,
          order: 5,
          priority: 'HIGH' as const,
        },
        {
          name: 'Engrase suspensión',
          triggerKm: 10000,
          estimatedTime: 0.3,
          order: 6,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspección suspensión',
          triggerKm: 10000,
          estimatedTime: 0.4,
          order: 7,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Engrase general',
          triggerKm: 10000,
          estimatedTime: 0.5,
          order: 8,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Control tension correas',
          triggerKm: 10000,
          estimatedTime: 0.3,
          order: 9,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Balanceo ruedas',
          triggerKm: 10000,
          estimatedTime: 0.7,
          order: 10,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion baterias',
          triggerKm: 10000,
          estimatedTime: 0.2,
          order: 11,
          priority: 'LOW' as const,
        },
      ],
    },
    {
      name: 'Mantenimiento Mayor + — 20,000 km',
      triggerKm: 20000,
      estimatedCost: 950000,
      estimatedTime: 5.0,
      priority: 'HIGH' as const,
      items: [
        {
          name: 'Cambio aceite motor',
          triggerKm: 20000,
          estimatedTime: 0.5,
          order: 1,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aceite',
          triggerKm: 20000,
          estimatedTime: 0.3,
          order: 2,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aire',
          triggerKm: 20000,
          estimatedTime: 0.2,
          order: 3,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Cambio filtro combustible',
          triggerKm: 20000,
          estimatedTime: 0.3,
          order: 4,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Calibración válvulas',
          triggerKm: 20000,
          estimatedTime: 1.0,
          order: 5,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspección general frenos',
          triggerKm: 20000,
          estimatedTime: 0.4,
          order: 6,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio líquido freno',
          triggerKm: 20000,
          estimatedTime: 0.5,
          order: 7,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspeccion escape sellos ruedas',
          triggerKm: 20000,
          estimatedTime: 0.3,
          order: 8,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Engrase suspensión',
          triggerKm: 20000,
          estimatedTime: 0.3,
          order: 9,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspección suspensión',
          triggerKm: 20000,
          estimatedTime: 0.4,
          order: 10,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Ajustar grapas fijacion muelles',
          triggerKm: 20000,
          estimatedTime: 0.3,
          order: 11,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Cambio aceite transmisión',
          triggerKm: 20000,
          estimatedTime: 1.0,
          order: 12,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Ajuste embrague',
          triggerKm: 20000,
          estimatedTime: 0.5,
          order: 13,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Rotación neumáticos',
          triggerKm: 20000,
          estimatedTime: 0.5,
          order: 14,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Balanceo ruedas',
          triggerKm: 20000,
          estimatedTime: 0.7,
          order: 15,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion baterias',
          triggerKm: 20000,
          estimatedTime: 0.2,
          order: 16,
          priority: 'LOW' as const,
        },
        {
          name: 'Limpieza terminales batería',
          triggerKm: 20000,
          estimatedTime: 0.2,
          order: 17,
          priority: 'LOW' as const,
        },
      ],
    },
    {
      name: 'Mantenimiento Mayor ++ — 40,000 km',
      triggerKm: 40000,
      estimatedCost: 1400000,
      estimatedTime: 7.0,
      priority: 'HIGH' as const,
      items: [
        {
          name: 'Cambio aceite motor',
          triggerKm: 40000,
          estimatedTime: 0.5,
          order: 1,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aceite',
          triggerKm: 40000,
          estimatedTime: 0.3,
          order: 2,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aire',
          triggerKm: 40000,
          estimatedTime: 0.2,
          order: 3,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Cambio filtro combustible',
          triggerKm: 40000,
          estimatedTime: 0.3,
          order: 4,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Calibración válvulas',
          triggerKm: 40000,
          estimatedTime: 1.0,
          order: 5,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspección general frenos',
          triggerKm: 40000,
          estimatedTime: 0.5,
          order: 6,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio líquido freno',
          triggerKm: 40000,
          estimatedTime: 0.5,
          order: 7,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspeccionar bandas freno',
          triggerKm: 40000,
          estimatedTime: 0.4,
          order: 8,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspeccion escape sellos ruedas',
          triggerKm: 40000,
          estimatedTime: 0.3,
          order: 9,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Engrase suspensión',
          triggerKm: 40000,
          estimatedTime: 0.3,
          order: 10,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspección suspensión',
          triggerKm: 40000,
          estimatedTime: 0.4,
          order: 11,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion fisuras muelles',
          triggerKm: 40000,
          estimatedTime: 0.3,
          order: 12,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion bujes suspension',
          triggerKm: 40000,
          estimatedTime: 0.3,
          order: 13,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Ajustar grapas fijacion muelles',
          triggerKm: 40000,
          estimatedTime: 0.3,
          order: 14,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Cambio aceite transmisión',
          triggerKm: 40000,
          estimatedTime: 1.0,
          order: 15,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Ajuste cardanes crucetas flanches',
          triggerKm: 40000,
          estimatedTime: 0.5,
          order: 16,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion respiradero transmision',
          triggerKm: 40000,
          estimatedTime: 0.2,
          order: 17,
          priority: 'LOW' as const,
        },
        {
          name: 'Cambio aceite diferencial',
          triggerKm: 40000,
          estimatedTime: 1.5,
          order: 18,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Ajuste juego dirección',
          triggerKm: 40000,
          estimatedTime: 0.4,
          order: 19,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion deposito direccion',
          triggerKm: 40000,
          estimatedTime: 0.2,
          order: 20,
          priority: 'LOW' as const,
        },
        {
          name: 'Rotación neumáticos',
          triggerKm: 40000,
          estimatedTime: 0.5,
          order: 21,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Balanceo ruedas',
          triggerKm: 40000,
          estimatedTime: 0.7,
          order: 22,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion filtro aire cabina',
          triggerKm: 40000,
          estimatedTime: 0.2,
          order: 23,
          priority: 'LOW' as const,
        },
        {
          name: 'Limpieza terminales batería',
          triggerKm: 40000,
          estimatedTime: 0.2,
          order: 24,
          priority: 'LOW' as const,
        },
      ],
    },
  ];

  // ─────────────────────────────────────────────────────────────────────────
  // KIT C — CAMIÓN MEDIANO (Hino 300 / Dutro)
  // Ritmo: 5K MENOR → 10K MAYOR → 20K MAYOR+ → 30K MAYOR++ → 60K COMPLETO
  // ─────────────────────────────────────────────────────────────────────────
  const getMediumTruckPackages = () => [
    {
      name: 'Mantenimiento Menor — 5,000 km',
      triggerKm: 5000,
      estimatedCost: 420000,
      estimatedTime: 2.5,
      priority: 'MEDIUM' as const,
      items: [
        {
          name: 'Cambio aceite motor',
          triggerKm: 5000,
          estimatedTime: 0.5,
          order: 1,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aceite',
          triggerKm: 5000,
          estimatedTime: 0.3,
          order: 2,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro combustible',
          triggerKm: 5000,
          estimatedTime: 0.3,
          order: 3,
          priority: 'HIGH' as const,
        },
        {
          name: 'Engrase general',
          triggerKm: 5000,
          estimatedTime: 0.5,
          order: 4,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Control guaya acelerador',
          triggerKm: 5000,
          estimatedTime: 0.2,
          order: 5,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspección general frenos',
          triggerKm: 5000,
          estimatedTime: 0.3,
          order: 6,
          priority: 'HIGH' as const,
        },
      ],
    },
    {
      name: 'Mantenimiento Mayor — 10,000 km',
      triggerKm: 10000,
      estimatedCost: 750000,
      estimatedTime: 4.0,
      priority: 'HIGH' as const,
      items: [
        {
          name: 'Cambio aceite motor',
          triggerKm: 10000,
          estimatedTime: 0.5,
          order: 1,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aceite',
          triggerKm: 10000,
          estimatedTime: 0.3,
          order: 2,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro combustible',
          triggerKm: 10000,
          estimatedTime: 0.3,
          order: 3,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aire',
          triggerKm: 10000,
          estimatedTime: 0.3,
          order: 4,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Engrase general',
          triggerKm: 10000,
          estimatedTime: 0.5,
          order: 5,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Control guaya acelerador',
          triggerKm: 10000,
          estimatedTime: 0.2,
          order: 6,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion radiador intercooler',
          triggerKm: 10000,
          estimatedTime: 0.3,
          order: 7,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Control tension correas',
          triggerKm: 10000,
          estimatedTime: 0.3,
          order: 8,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion linea admision',
          triggerKm: 10000,
          estimatedTime: 0.2,
          order: 9,
          priority: 'LOW' as const,
        },
        {
          name: 'Inspeccion soporte motor transmision',
          triggerKm: 10000,
          estimatedTime: 0.2,
          order: 10,
          priority: 'LOW' as const,
        },
        {
          name: 'Ajuste embrague',
          triggerKm: 10000,
          estimatedTime: 0.5,
          order: 11,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspección general frenos',
          triggerKm: 10000,
          estimatedTime: 0.4,
          order: 12,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspeccion cilindro freno',
          triggerKm: 10000,
          estimatedTime: 0.3,
          order: 13,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion escape sellos ruedas',
          triggerKm: 10000,
          estimatedTime: 0.3,
          order: 14,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Engrase suspensión',
          triggerKm: 10000,
          estimatedTime: 0.4,
          order: 15,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion fisuras muelles',
          triggerKm: 10000,
          estimatedTime: 0.3,
          order: 16,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion bujes suspension',
          triggerKm: 10000,
          estimatedTime: 0.3,
          order: 17,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion conexion alternador arranque',
          triggerKm: 10000,
          estimatedTime: 0.2,
          order: 18,
          priority: 'LOW' as const,
        },
        {
          name: 'Inspeccion baterias',
          triggerKm: 10000,
          estimatedTime: 0.2,
          order: 19,
          priority: 'LOW' as const,
        },
      ],
    },
    {
      name: 'Mantenimiento Mayor + — 20,000 km',
      triggerKm: 20000,
      estimatedCost: 1100000,
      estimatedTime: 5.5,
      priority: 'HIGH' as const,
      items: [
        {
          name: 'Cambio aceite motor',
          triggerKm: 20000,
          estimatedTime: 0.5,
          order: 1,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aceite',
          triggerKm: 20000,
          estimatedTime: 0.3,
          order: 2,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro combustible',
          triggerKm: 20000,
          estimatedTime: 0.3,
          order: 3,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aire',
          triggerKm: 20000,
          estimatedTime: 0.3,
          order: 4,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Engrase general',
          triggerKm: 20000,
          estimatedTime: 0.5,
          order: 5,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Control guaya acelerador',
          triggerKm: 20000,
          estimatedTime: 0.2,
          order: 6,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion radiador intercooler',
          triggerKm: 20000,
          estimatedTime: 0.3,
          order: 7,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Control tension correas',
          triggerKm: 20000,
          estimatedTime: 0.3,
          order: 8,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion linea admision',
          triggerKm: 20000,
          estimatedTime: 0.2,
          order: 9,
          priority: 'LOW' as const,
        },
        {
          name: 'Cambio aceite transmisión',
          triggerKm: 20000,
          estimatedTime: 1.0,
          order: 10,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Ajuste embrague',
          triggerKm: 20000,
          estimatedTime: 0.5,
          order: 11,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Ajuste cardanes crucetas flanches',
          triggerKm: 20000,
          estimatedTime: 0.5,
          order: 12,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion respiradero transmision',
          triggerKm: 20000,
          estimatedTime: 0.2,
          order: 13,
          priority: 'LOW' as const,
        },
        {
          name: 'Inspección general frenos',
          triggerKm: 20000,
          estimatedTime: 0.4,
          order: 14,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspeccionar bandas freno',
          triggerKm: 20000,
          estimatedTime: 0.4,
          order: 15,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspeccion cilindro freno',
          triggerKm: 20000,
          estimatedTime: 0.3,
          order: 16,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion escape sellos ruedas',
          triggerKm: 20000,
          estimatedTime: 0.3,
          order: 17,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Engrase suspensión',
          triggerKm: 20000,
          estimatedTime: 0.4,
          order: 18,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion fisuras muelles',
          triggerKm: 20000,
          estimatedTime: 0.3,
          order: 19,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion bujes suspension',
          triggerKm: 20000,
          estimatedTime: 0.3,
          order: 20,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Ajustar grapas fijacion muelles',
          triggerKm: 20000,
          estimatedTime: 0.3,
          order: 21,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion deposito direccion',
          triggerKm: 20000,
          estimatedTime: 0.2,
          order: 22,
          priority: 'LOW' as const,
        },
        {
          name: 'Engrase rodamientos',
          triggerKm: 20000,
          estimatedTime: 0.4,
          order: 23,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion filtro aire cabina',
          triggerKm: 20000,
          estimatedTime: 0.2,
          order: 24,
          priority: 'LOW' as const,
        },
        {
          name: 'Inspeccion conexion alternador arranque',
          triggerKm: 20000,
          estimatedTime: 0.2,
          order: 25,
          priority: 'LOW' as const,
        },
        {
          name: 'Inspeccion baterias',
          triggerKm: 20000,
          estimatedTime: 0.2,
          order: 26,
          priority: 'LOW' as const,
        },
        {
          name: 'Rotación neumáticos',
          triggerKm: 20000,
          estimatedTime: 0.5,
          order: 27,
          priority: 'MEDIUM' as const,
        },
      ],
    },
    {
      name: 'Mantenimiento Mayor ++ — 30,000 km',
      triggerKm: 30000,
      estimatedCost: 1450000,
      estimatedTime: 7.0,
      priority: 'HIGH' as const,
      items: [
        {
          name: 'Cambio aceite motor',
          triggerKm: 30000,
          estimatedTime: 0.5,
          order: 1,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aceite',
          triggerKm: 30000,
          estimatedTime: 0.3,
          order: 2,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro combustible',
          triggerKm: 30000,
          estimatedTime: 0.3,
          order: 3,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aire',
          triggerKm: 30000,
          estimatedTime: 0.3,
          order: 4,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Calibración válvulas',
          triggerKm: 30000,
          estimatedTime: 1.0,
          order: 5,
          priority: 'HIGH' as const,
        },
        {
          name: 'Engrase general',
          triggerKm: 30000,
          estimatedTime: 0.5,
          order: 6,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Control guaya acelerador',
          triggerKm: 30000,
          estimatedTime: 0.2,
          order: 7,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion radiador intercooler',
          triggerKm: 30000,
          estimatedTime: 0.3,
          order: 8,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Control tension correas',
          triggerKm: 30000,
          estimatedTime: 0.3,
          order: 9,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Cambio aceite transmisión',
          triggerKm: 30000,
          estimatedTime: 1.0,
          order: 10,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Ajuste embrague',
          triggerKm: 30000,
          estimatedTime: 0.5,
          order: 11,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Ajuste cardanes crucetas flanches',
          triggerKm: 30000,
          estimatedTime: 0.5,
          order: 12,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion respiradero transmision',
          triggerKm: 30000,
          estimatedTime: 0.2,
          order: 13,
          priority: 'LOW' as const,
        },
        {
          name: 'Inspección general frenos',
          triggerKm: 30000,
          estimatedTime: 0.4,
          order: 14,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio líquido freno',
          triggerKm: 30000,
          estimatedTime: 0.5,
          order: 15,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspeccionar bandas freno',
          triggerKm: 30000,
          estimatedTime: 0.4,
          order: 16,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspeccion cilindro freno',
          triggerKm: 30000,
          estimatedTime: 0.3,
          order: 17,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Engrase suspensión',
          triggerKm: 30000,
          estimatedTime: 0.4,
          order: 18,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspección suspensión',
          triggerKm: 30000,
          estimatedTime: 0.3,
          order: 19,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion fisuras muelles',
          triggerKm: 30000,
          estimatedTime: 0.3,
          order: 20,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion bujes suspension',
          triggerKm: 30000,
          estimatedTime: 0.3,
          order: 21,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Ajustar grapas fijacion muelles',
          triggerKm: 30000,
          estimatedTime: 0.3,
          order: 22,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Ajuste juego dirección',
          triggerKm: 30000,
          estimatedTime: 0.4,
          order: 23,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion deposito direccion',
          triggerKm: 30000,
          estimatedTime: 0.2,
          order: 24,
          priority: 'LOW' as const,
        },
        {
          name: 'Engrase rodamientos',
          triggerKm: 30000,
          estimatedTime: 0.4,
          order: 25,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion filtro aire cabina',
          triggerKm: 30000,
          estimatedTime: 0.2,
          order: 26,
          priority: 'LOW' as const,
        },
        {
          name: 'Limpieza terminales batería',
          triggerKm: 30000,
          estimatedTime: 0.2,
          order: 27,
          priority: 'LOW' as const,
        },
        {
          name: 'Rotación neumáticos',
          triggerKm: 30000,
          estimatedTime: 0.5,
          order: 28,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Balanceo ruedas',
          triggerKm: 30000,
          estimatedTime: 0.7,
          order: 29,
          priority: 'MEDIUM' as const,
        },
      ],
    },
    {
      name: 'Mantenimiento Completo — 60,000 km',
      triggerKm: 60000,
      estimatedCost: 2200000,
      estimatedTime: 9.0,
      priority: 'HIGH' as const,
      items: [
        {
          name: 'Cambio aceite motor',
          triggerKm: 60000,
          estimatedTime: 0.5,
          order: 1,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aceite',
          triggerKm: 60000,
          estimatedTime: 0.3,
          order: 2,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro combustible',
          triggerKm: 60000,
          estimatedTime: 0.3,
          order: 3,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aire',
          triggerKm: 60000,
          estimatedTime: 0.3,
          order: 4,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Calibración válvulas',
          triggerKm: 60000,
          estimatedTime: 1.0,
          order: 5,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspeccion turbocharger',
          triggerKm: 60000,
          estimatedTime: 0.5,
          order: 6,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspeccion bomba inyectores',
          triggerKm: 60000,
          estimatedTime: 0.5,
          order: 7,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspeccion radiador intercooler',
          triggerKm: 60000,
          estimatedTime: 0.3,
          order: 8,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion mangueras refrigerante',
          triggerKm: 60000,
          estimatedTime: 0.3,
          order: 9,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Control tension correas',
          triggerKm: 60000,
          estimatedTime: 0.3,
          order: 10,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Engrase general',
          triggerKm: 60000,
          estimatedTime: 0.5,
          order: 11,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Cambio aceite transmisión',
          triggerKm: 60000,
          estimatedTime: 1.0,
          order: 12,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Ajuste cardanes crucetas flanches',
          triggerKm: 60000,
          estimatedTime: 0.5,
          order: 13,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion diferencial',
          triggerKm: 60000,
          estimatedTime: 0.4,
          order: 14,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspección general frenos',
          triggerKm: 60000,
          estimatedTime: 0.4,
          order: 15,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio líquido freno',
          triggerKm: 60000,
          estimatedTime: 0.5,
          order: 16,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspeccionar bandas freno',
          triggerKm: 60000,
          estimatedTime: 0.4,
          order: 17,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspeccion cilindro freno',
          triggerKm: 60000,
          estimatedTime: 0.3,
          order: 18,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Engrase suspensión',
          triggerKm: 60000,
          estimatedTime: 0.4,
          order: 19,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion fisuras muelles',
          triggerKm: 60000,
          estimatedTime: 0.3,
          order: 20,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion bujes suspension',
          triggerKm: 60000,
          estimatedTime: 0.3,
          order: 21,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Ajustar grapas fijacion muelles',
          triggerKm: 60000,
          estimatedTime: 0.3,
          order: 22,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Ajuste juego dirección',
          triggerKm: 60000,
          estimatedTime: 0.4,
          order: 23,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion deposito direccion',
          triggerKm: 60000,
          estimatedTime: 0.2,
          order: 24,
          priority: 'LOW' as const,
        },
        {
          name: 'Engrase rodamientos',
          triggerKm: 60000,
          estimatedTime: 0.4,
          order: 25,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion filtro aire cabina',
          triggerKm: 60000,
          estimatedTime: 0.2,
          order: 26,
          priority: 'LOW' as const,
        },
        {
          name: 'Limpieza terminales batería',
          triggerKm: 60000,
          estimatedTime: 0.2,
          order: 27,
          priority: 'LOW' as const,
        },
        {
          name: 'Inspeccion conexion alternador arranque',
          triggerKm: 60000,
          estimatedTime: 0.2,
          order: 28,
          priority: 'LOW' as const,
        },
        {
          name: 'Rotación neumáticos',
          triggerKm: 60000,
          estimatedTime: 0.5,
          order: 29,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Balanceo ruedas',
          triggerKm: 60000,
          estimatedTime: 0.7,
          order: 30,
          priority: 'MEDIUM' as const,
        },
      ],
    },
  ];

  // ─────────────────────────────────────────────────────────────────────────
  // KIT D — CAMIÓN PESADO / TRACTOCAMIÓN (International 7400 / WorkStar)
  // Ritmo: 10K MENOR → 25K MAYOR → 50K MAYOR+ → 100K COMPLETO
  // ─────────────────────────────────────────────────────────────────────────
  const getHeavyTruckPackages = () => [
    {
      name: 'Mantenimiento Menor — 10,000 km',
      triggerKm: 10000,
      estimatedCost: 800000,
      estimatedTime: 3.0,
      priority: 'MEDIUM' as const,
      items: [
        {
          name: 'Cambio aceite motor',
          triggerKm: 10000,
          estimatedTime: 1.0,
          order: 1,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aceite',
          triggerKm: 10000,
          estimatedTime: 0.5,
          order: 2,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro combustible',
          triggerKm: 10000,
          estimatedTime: 0.5,
          order: 3,
          priority: 'HIGH' as const,
        },
        {
          name: 'Engrase general',
          triggerKm: 10000,
          estimatedTime: 1.0,
          order: 4,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Drenar tanques de aire',
          triggerKm: 10000,
          estimatedTime: 0.3,
          order: 5,
          priority: 'HIGH' as const,
        },
        {
          name: 'Drenaje agua separador combustible',
          triggerKm: 10000,
          estimatedTime: 0.2,
          order: 6,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspección general frenos',
          triggerKm: 10000,
          estimatedTime: 0.4,
          order: 7,
          priority: 'HIGH' as const,
        },
      ],
    },
    {
      name: 'Mantenimiento Mayor — 25,000 km',
      triggerKm: 25000,
      estimatedCost: 1600000,
      estimatedTime: 6.0,
      priority: 'HIGH' as const,
      items: [
        {
          name: 'Cambio aceite motor',
          triggerKm: 25000,
          estimatedTime: 1.0,
          order: 1,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aceite',
          triggerKm: 25000,
          estimatedTime: 0.5,
          order: 2,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro combustible',
          triggerKm: 25000,
          estimatedTime: 0.5,
          order: 3,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aire',
          triggerKm: 25000,
          estimatedTime: 0.5,
          order: 4,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Filtro secador de aire',
          triggerKm: 25000,
          estimatedTime: 0.4,
          order: 5,
          priority: 'HIGH' as const,
        },
        {
          name: 'Engrase general',
          triggerKm: 25000,
          estimatedTime: 1.0,
          order: 6,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Control guaya acelerador',
          triggerKm: 25000,
          estimatedTime: 0.2,
          order: 7,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion radiador intercooler',
          triggerKm: 25000,
          estimatedTime: 0.3,
          order: 8,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Control tension correas',
          triggerKm: 25000,
          estimatedTime: 0.3,
          order: 9,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Drenar tanques de aire',
          triggerKm: 25000,
          estimatedTime: 0.3,
          order: 10,
          priority: 'HIGH' as const,
        },
        {
          name: 'Revision frenos de aire',
          triggerKm: 25000,
          estimatedTime: 0.5,
          order: 11,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspeccion valvula alivio freno',
          triggerKm: 25000,
          estimatedTime: 0.3,
          order: 12,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspección general frenos',
          triggerKm: 25000,
          estimatedTime: 0.4,
          order: 13,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspeccion escape sellos ruedas',
          triggerKm: 25000,
          estimatedTime: 0.3,
          order: 14,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Engrase suspensión',
          triggerKm: 25000,
          estimatedTime: 0.5,
          order: 15,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion fisuras muelles',
          triggerKm: 25000,
          estimatedTime: 0.3,
          order: 16,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion bujes suspension',
          triggerKm: 25000,
          estimatedTime: 0.3,
          order: 17,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Ajustar grapas fijacion muelles',
          triggerKm: 25000,
          estimatedTime: 0.3,
          order: 18,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion conexion alternador arranque',
          triggerKm: 25000,
          estimatedTime: 0.2,
          order: 19,
          priority: 'LOW' as const,
        },
        {
          name: 'Inspeccion baterias',
          triggerKm: 25000,
          estimatedTime: 0.2,
          order: 20,
          priority: 'LOW' as const,
        },
        {
          name: 'Drenaje agua separador combustible',
          triggerKm: 25000,
          estimatedTime: 0.2,
          order: 21,
          priority: 'HIGH' as const,
        },
      ],
    },
    {
      name: 'Mantenimiento Mayor + — 50,000 km',
      triggerKm: 50000,
      estimatedCost: 2500000,
      estimatedTime: 9.0,
      priority: 'HIGH' as const,
      items: [
        {
          name: 'Cambio aceite motor',
          triggerKm: 50000,
          estimatedTime: 1.0,
          order: 1,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aceite',
          triggerKm: 50000,
          estimatedTime: 0.5,
          order: 2,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro combustible',
          triggerKm: 50000,
          estimatedTime: 0.5,
          order: 3,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aire',
          triggerKm: 50000,
          estimatedTime: 0.5,
          order: 4,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Filtro secador de aire',
          triggerKm: 50000,
          estimatedTime: 0.4,
          order: 5,
          priority: 'HIGH' as const,
        },
        {
          name: 'Calibración válvulas',
          triggerKm: 50000,
          estimatedTime: 1.5,
          order: 6,
          priority: 'HIGH' as const,
        },
        {
          name: 'Engrase general',
          triggerKm: 50000,
          estimatedTime: 1.0,
          order: 7,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Control guaya acelerador',
          triggerKm: 50000,
          estimatedTime: 0.2,
          order: 8,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion radiador intercooler',
          triggerKm: 50000,
          estimatedTime: 0.3,
          order: 9,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Control tension correas',
          triggerKm: 50000,
          estimatedTime: 0.3,
          order: 10,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Drenar tanques de aire',
          triggerKm: 50000,
          estimatedTime: 0.3,
          order: 11,
          priority: 'HIGH' as const,
        },
        {
          name: 'Revision frenos de aire',
          triggerKm: 50000,
          estimatedTime: 0.5,
          order: 12,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspeccion valvula alivio freno',
          triggerKm: 50000,
          estimatedTime: 0.3,
          order: 13,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspección general frenos',
          triggerKm: 50000,
          estimatedTime: 0.4,
          order: 14,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio líquido freno',
          triggerKm: 50000,
          estimatedTime: 0.5,
          order: 15,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspeccionar bandas freno',
          triggerKm: 50000,
          estimatedTime: 0.4,
          order: 16,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspeccion cilindro freno',
          triggerKm: 50000,
          estimatedTime: 0.3,
          order: 17,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion tambores discos freno',
          triggerKm: 50000,
          estimatedTime: 0.4,
          order: 18,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion escape sellos ruedas',
          triggerKm: 50000,
          estimatedTime: 0.3,
          order: 19,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Cambio aceite transmisión',
          triggerKm: 50000,
          estimatedTime: 1.5,
          order: 20,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Ajuste embrague',
          triggerKm: 50000,
          estimatedTime: 0.5,
          order: 21,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Ajuste cardanes crucetas flanches',
          triggerKm: 50000,
          estimatedTime: 0.8,
          order: 22,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion respiradero transmision',
          triggerKm: 50000,
          estimatedTime: 0.2,
          order: 23,
          priority: 'LOW' as const,
        },
        {
          name: 'Engrase suspensión',
          triggerKm: 50000,
          estimatedTime: 0.5,
          order: 24,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion fisuras muelles',
          triggerKm: 50000,
          estimatedTime: 0.3,
          order: 25,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion bujes suspension',
          triggerKm: 50000,
          estimatedTime: 0.3,
          order: 26,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Ajustar grapas fijacion muelles',
          triggerKm: 50000,
          estimatedTime: 0.3,
          order: 27,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Ajuste juego dirección',
          triggerKm: 50000,
          estimatedTime: 0.4,
          order: 28,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion deposito direccion',
          triggerKm: 50000,
          estimatedTime: 0.2,
          order: 29,
          priority: 'LOW' as const,
        },
        {
          name: 'Engrase rodamientos',
          triggerKm: 50000,
          estimatedTime: 0.5,
          order: 30,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Limpieza terminales batería',
          triggerKm: 50000,
          estimatedTime: 0.2,
          order: 31,
          priority: 'LOW' as const,
        },
        {
          name: 'Drenaje agua separador combustible',
          triggerKm: 50000,
          estimatedTime: 0.2,
          order: 32,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspeccion filtro aire cabina',
          triggerKm: 50000,
          estimatedTime: 0.2,
          order: 33,
          priority: 'LOW' as const,
        },
        {
          name: 'Rotación neumáticos',
          triggerKm: 50000,
          estimatedTime: 0.7,
          order: 34,
          priority: 'MEDIUM' as const,
        },
      ],
    },
    {
      name: 'Mantenimiento Completo — 100,000 km',
      triggerKm: 100000,
      estimatedCost: 4500000,
      estimatedTime: 14.0,
      priority: 'HIGH' as const,
      items: [
        {
          name: 'Cambio aceite motor',
          triggerKm: 100000,
          estimatedTime: 1.0,
          order: 1,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aceite',
          triggerKm: 100000,
          estimatedTime: 0.5,
          order: 2,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro combustible',
          triggerKm: 100000,
          estimatedTime: 0.5,
          order: 3,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio filtro aire',
          triggerKm: 100000,
          estimatedTime: 0.5,
          order: 4,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Filtro secador de aire',
          triggerKm: 100000,
          estimatedTime: 0.4,
          order: 5,
          priority: 'HIGH' as const,
        },
        {
          name: 'Calibración válvulas',
          triggerKm: 100000,
          estimatedTime: 1.5,
          order: 6,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspeccion turbocharger',
          triggerKm: 100000,
          estimatedTime: 0.8,
          order: 7,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspeccion bomba inyectores',
          triggerKm: 100000,
          estimatedTime: 0.8,
          order: 8,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspeccion radiador refrigeracion',
          triggerKm: 100000,
          estimatedTime: 0.4,
          order: 9,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion mangueras refrigerante',
          triggerKm: 100000,
          estimatedTime: 0.3,
          order: 10,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion linea admision',
          triggerKm: 100000,
          estimatedTime: 0.2,
          order: 11,
          priority: 'LOW' as const,
        },
        {
          name: 'Control tension correas',
          triggerKm: 100000,
          estimatedTime: 0.3,
          order: 12,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Engrase general',
          triggerKm: 100000,
          estimatedTime: 1.0,
          order: 13,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Drenar tanques de aire',
          triggerKm: 100000,
          estimatedTime: 0.3,
          order: 14,
          priority: 'HIGH' as const,
        },
        {
          name: 'Revision frenos de aire',
          triggerKm: 100000,
          estimatedTime: 0.5,
          order: 15,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspeccion valvula alivio freno',
          triggerKm: 100000,
          estimatedTime: 0.3,
          order: 16,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspección general frenos',
          triggerKm: 100000,
          estimatedTime: 0.5,
          order: 17,
          priority: 'HIGH' as const,
        },
        {
          name: 'Cambio líquido freno',
          triggerKm: 100000,
          estimatedTime: 0.5,
          order: 18,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspeccionar bandas freno',
          triggerKm: 100000,
          estimatedTime: 0.4,
          order: 19,
          priority: 'HIGH' as const,
        },
        {
          name: 'Inspeccion cilindro freno',
          triggerKm: 100000,
          estimatedTime: 0.3,
          order: 20,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion tambores discos freno',
          triggerKm: 100000,
          estimatedTime: 0.4,
          order: 21,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion escape sellos ruedas',
          triggerKm: 100000,
          estimatedTime: 0.3,
          order: 22,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Cambio aceite transmisión',
          triggerKm: 100000,
          estimatedTime: 1.5,
          order: 23,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Ajuste embrague',
          triggerKm: 100000,
          estimatedTime: 0.5,
          order: 24,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Ajuste cardanes crucetas flanches',
          triggerKm: 100000,
          estimatedTime: 0.8,
          order: 25,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion diferencial',
          triggerKm: 100000,
          estimatedTime: 0.5,
          order: 26,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Cambio aceite diferencial',
          triggerKm: 100000,
          estimatedTime: 1.5,
          order: 27,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion respiradero transmision',
          triggerKm: 100000,
          estimatedTime: 0.2,
          order: 28,
          priority: 'LOW' as const,
        },
        {
          name: 'Inspeccion soporte motor transmision',
          triggerKm: 100000,
          estimatedTime: 0.2,
          order: 29,
          priority: 'LOW' as const,
        },
        {
          name: 'Engrase suspensión',
          triggerKm: 100000,
          estimatedTime: 0.5,
          order: 30,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion fisuras muelles',
          triggerKm: 100000,
          estimatedTime: 0.3,
          order: 31,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion bujes suspension',
          triggerKm: 100000,
          estimatedTime: 0.3,
          order: 32,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Ajustar grapas fijacion muelles',
          triggerKm: 100000,
          estimatedTime: 0.3,
          order: 33,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Ajuste juego dirección',
          triggerKm: 100000,
          estimatedTime: 0.4,
          order: 34,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Inspeccion deposito direccion',
          triggerKm: 100000,
          estimatedTime: 0.2,
          order: 35,
          priority: 'LOW' as const,
        },
        {
          name: 'Engrase rodamientos',
          triggerKm: 100000,
          estimatedTime: 0.5,
          order: 36,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Limpieza terminales batería',
          triggerKm: 100000,
          estimatedTime: 0.2,
          order: 37,
          priority: 'LOW' as const,
        },
        {
          name: 'Inspeccion conexion alternador arranque',
          triggerKm: 100000,
          estimatedTime: 0.2,
          order: 38,
          priority: 'LOW' as const,
        },
        {
          name: 'Inspeccion baterias',
          triggerKm: 100000,
          estimatedTime: 0.2,
          order: 39,
          priority: 'LOW' as const,
        },
        {
          name: 'Inspeccion filtro aire cabina',
          triggerKm: 100000,
          estimatedTime: 0.2,
          order: 40,
          priority: 'LOW' as const,
        },
        {
          name: 'Drenaje agua separador combustible',
          triggerKm: 100000,
          estimatedTime: 0.2,
          order: 41,
          priority: 'HIGH' as const,
        },
        {
          name: 'Rotación neumáticos',
          triggerKm: 100000,
          estimatedTime: 0.7,
          order: 42,
          priority: 'MEDIUM' as const,
        },
        {
          name: 'Balanceo ruedas',
          triggerKm: 100000,
          estimatedTime: 0.8,
          order: 43,
          priority: 'MEDIUM' as const,
        },
      ],
    },
  ];

  // ─────────────────────────────────────────────────────────────────────────
  // Mapeo VehicleType → Kit
  // ─────────────────────────────────────────────────────────────────────────
  const LIGHT_TYPES = ['Automóvil', 'Campero', 'SUV'];
  const PICKUP_TYPES = [
    'Camioneta',
    'Furgón',
    'Microbús',
    'Vehículo de Emergencia',
  ];
  const MEDIUM_TYPES = ['Camión Mediano', 'Buseta', 'Bus'];
  const HEAVY_TYPES = ['Camión Pesado', 'Tractocamión', 'Volqueta'];

  const VEHICLE_TYPES = await prisma.vehicleType.findMany({
    where: { tenantId: null, isGlobal: true },
  });

  for (const vt of VEHICLE_TYPES) {
    const templateName = `Plan Base — ${vt.name}`;

    const existing = await prisma.maintenanceTemplate.findFirst({
      where: { name: templateName, tenantId: null },
    });

    if (existing) {
      console.log(
        `   [MANT]   ↳ Template ya existe para ${vt.name}, omitiendo.`
      );
      continue;
    }

    let pkgs: ReturnType<typeof getBasicPackages> = [];
    if (HEAVY_TYPES.includes(vt.name)) pkgs = getHeavyTruckPackages();
    else if (MEDIUM_TYPES.includes(vt.name)) pkgs = getMediumTruckPackages();
    else if (PICKUP_TYPES.includes(vt.name)) pkgs = getPickupPackages();
    else if (LIGHT_TYPES.includes(vt.name)) pkgs = getBasicPackages();
    else {
      pkgs = [
        {
          name: 'Mantenimiento General — 10,000 km',
          triggerKm: 10000,
          estimatedCost: 150000,
          estimatedTime: 2.0,
          priority: 'MEDIUM' as const,
          items: [
            {
              name: 'Cambio aceite motor',
              triggerKm: 10000,
              estimatedTime: 1.0,
              order: 1,
              priority: 'HIGH' as const,
            },
            {
              name: 'Cambio filtro aceite',
              triggerKm: 10000,
              estimatedTime: 0.5,
              order: 2,
              priority: 'HIGH' as const,
            },
            {
              name: 'Engrase general',
              triggerKm: 10000,
              estimatedTime: 1.0,
              order: 3,
              priority: 'MEDIUM' as const,
            },
            {
              name: 'Inspección general frenos',
              triggerKm: 10000,
              estimatedTime: 0.4,
              order: 4,
              priority: 'HIGH' as const,
            },
          ],
        },
      ];
    }

    const packagesData = pkgs.map(pkg => {
      const dbItems = pkg.items
        .map(item => ({
          mantItemId: resolveItem(item.name),
          triggerKm: item.triggerKm,
          estimatedTime: item.estimatedTime,
          order: item.order,
          priority: item.priority,
          status: 'ACTIVE' as const,
        }))
        .filter(item => item.mantItemId !== '');

      return {
        name: pkg.name,
        triggerKm: pkg.triggerKm,
        estimatedCost: pkg.estimatedCost,
        estimatedTime: pkg.estimatedTime,
        priority: pkg.priority,
        packageType: 'PREVENTIVE' as const,
        status: 'ACTIVE' as const,
        packageItems: { create: dbItems },
      };
    });

    const validPackages = packagesData.filter(
      pkg => pkg.packageItems.create.length > 0
    );

    await prisma.maintenanceTemplate.create({
      data: {
        name: templateName,
        description: `Plan de mantenimiento preventivo base para ${vt.name}. Diseñado bajo estándares de fabricantes. Clona y adapta a tu flota.`,
        vehicleTypeId: vt.id,
        tenantId: null,
        isGlobal: true,
        version: '1.0',
        isDefault: true,
        packages: { create: validPackages },
      },
    });

    console.log(
      `   [MANT]   ↳ Creado: ${templateName} (${validPackages.length} paquetes)`
    );
  }

  console.log(
    '   [MANT] MaintenanceTemplates globales con ritmo Mayor/Menor completados.'
  );
}
