import { PrismaClient } from '@prisma/client';

// Catálogo curado de marcas y líneas para Colombia
// Fuente: RUNT open data (datos.gov.co) + catálogo verificado manualmente
// Solo marcas homologadas que aparecen en tarjeta de propiedad colombiana

const CATALOG: Record<string, string[]> = {
  // ── AUTOMÓVILES / CAMIONETAS / SUVs ─────────────────────────────────────
  TOYOTA: [
    'COROLLA',
    'YARIS',
    'CAMRY',
    'HILUX',
    'LAND CRUISER PRADO',
    'LAND CRUISER 70',
    'FORTUNER',
    'RAV4',
    'C-HR',
    'AVANZA',
    'HIACE',
    'DYNA',
    'LAND CRUISER 200',
    'RUSH',
    'TERIOS',
  ],
  CHEVROLET: [
    'ONIX',
    'SPARK',
    'TRACKER',
    'CAPTIVA',
    'TRAVERSE',
    'EQUINOX',
    'BLAZER',
    'COLORADO',
    'SILVERADO',
    'D-MAX',
    'CRUZE',
    'SAIL',
    'S10',
    'NHR',
    'NPR',
    'NQR',
    'NLR',
    'FSR',
  ],
  RENAULT: [
    'KWID',
    'SANDERO',
    'LOGAN',
    'STEPWAY',
    'DUSTER',
    'OROCH',
    'KOLEOS',
    'CAPTUR',
    'KANGOO',
    'MASTER',
    'TRAFIC',
    'MEGANE',
  ],
  KIA: [
    'PICANTO',
    'RIO',
    'SOUL',
    'STONIC',
    'SELTOS',
    'SPORTAGE',
    'SORENTO',
    'CARNIVAL',
    'TELLURIDE',
    'MOHAVE',
    'BESTA',
    'K2500',
    'K3000',
  ],
  HYUNDAI: [
    'GRAND I10',
    'I10',
    'I20',
    'ACCENT',
    'ELANTRA',
    'IONIQ',
    'CRETA',
    'TUCSON',
    'SANTA FE',
    'PALISADE',
    'H1',
    'H100',
    'HD65',
    'HD78',
    'HD120',
  ],
  MAZDA: [
    'MAZDA2',
    'MAZDA3',
    'MAZDA6',
    'CX-3',
    'CX-5',
    'CX-30',
    'CX-60',
    'BT-50',
  ],
  FORD: [
    'FIESTA',
    'FOCUS',
    'MUSTANG',
    'ESCAPE',
    'ECOSPORT',
    'EDGE',
    'EXPLORER',
    'EXPEDITION',
    'BRONCO',
    'RANGER',
    'F-150',
    'F-250',
    'F-350',
    'F-450',
    'TRANSIT',
    'TRANSIT CONNECT',
  ],
  NISSAN: [
    'VERSA',
    'SENTRA',
    'ALTIMA',
    'KICKS',
    'X-TRAIL',
    'PATHFINDER',
    'ARMADA',
    'FRONTIER',
    'NAVARA',
    'URVAN',
    'NV350',
    'PATROL',
  ],
  VOLKSWAGEN: [
    'POLO',
    'GOLF',
    'TIGUAN',
    'T-CROSS',
    'T-ROC',
    'AMAROK',
    'CRAFTER',
    'TRANSPORTER',
    'CARAVELLE',
  ],
  MITSUBISHI: [
    'LANCER',
    'GALANT',
    'OUTLANDER',
    'ASX',
    'ECLIPSE CROSS',
    'MONTERO SPORT',
    'L200',
    'L300',
    'CANTER',
  ],
  JEEP: [
    'RENEGADE',
    'COMPASS',
    'WRANGLER',
    'CHEROKEE',
    'GRAND CHEROKEE',
    'GLADIATOR',
    'WILLYS',
  ],
  DODGE: ['JOURNEY', 'DURANGO', 'RAM 700', 'RAM 1500', 'RAM 2500', 'RAM 3500'],
  RAM: ['700', '1500', '2500', '3500', 'PROMASTER', 'PROMASTER CITY'],
  SUZUKI: [
    'ALTO',
    'SWIFT',
    'BALENO',
    'VITARA',
    'GRAND VITARA',
    'JIMNY',
    'S-PRESSO',
    'ERTIGA',
    'CIAZ',
    'IGNIS',
  ],
  FIAT: [
    'MOBI',
    'UNO',
    'CRONOS',
    'ARGO',
    'FASTBACK',
    'PULSE',
    'TORO',
    'DUCATO',
  ],
  PEUGEOT: ['208', '2008', '301', '308', '3008', '5008', 'PARTNER', 'BOXER'],
  CITROEN: ['C3', 'C4 CACTUS', 'C5 AIRCROSS', 'BERLINGO', 'JUMPY', 'JUMPER'],
  'LAND ROVER': [
    'DEFENDER',
    'DISCOVERY',
    'DISCOVERY SPORT',
    'RANGE ROVER',
    'RANGE ROVER SPORT',
    'RANGE ROVER EVOQUE',
    'RANGE ROVER VELAR',
  ],
  SUBARU: ['IMPREZA', 'FORESTER', 'OUTBACK', 'XV', 'CROSSTREK'],
  HONDA: [
    'CIVIC',
    'ACCORD',
    'CR-V',
    'HR-V',
    'PILOT',
    'PASSPORT',
    'RIDGELINE',
    'FIT',
    'BR-V',
  ],
  BMW: [
    'SERIE 1',
    'SERIE 2',
    'SERIE 3',
    'SERIE 5',
    'SERIE 7',
    'X1',
    'X2',
    'X3',
    'X4',
    'X5',
    'X6',
    'X7',
  ],
  AUDI: ['A3', 'A4', 'A5', 'A6', 'Q3', 'Q5', 'Q7', 'Q8', 'E-TRON'],
  'MERCEDES BENZ': [
    'A200',
    'C300',
    'E300',
    'GLA',
    'GLC',
    'GLE',
    'GLS',
    'VITO',
    'SPRINTER',
    'CITO',
    'OF1418',
    'OF1721',
    'ACTROS',
    'ATEGO',
    'AXOR',
  ],
  VOLVO: [
    'XC40',
    'XC60',
    'XC90',
    'S60',
    'V60',
    'FH',
    'FM',
    'FMX',
    'FL',
    'FE',
    'VNL',
  ],
  MG: ['ZS', 'HS', 'RX5', 'RX8', '5', '4', 'MARVEL R'],
  GEELY: ['EMGRAND', 'COOLRAY', 'AZKARRA', 'OKAVANGO', 'ATLAS', 'ATLAS PRO'],
  CHERY: ['QQ', 'ARRIZO 5', 'TIGGO 2', 'TIGGO 4', 'TIGGO 7', 'TIGGO 8'],
  JAC: ['S2', 'S3', 'S7', 'J7', 'EJS1', 'T6', 'T8', 'N35', 'N55', 'N75'],
  BYD: ['YUAN PLUS', 'DOLPHIN', 'ATTO 3', 'SONG PLUS', 'HAN', 'TANG', 'SEAL'],
  'GREAT WALL': ['HAVAL H6', 'HAVAL H9', 'HAVAL JOLION', 'POER', 'WINGLE 7'],
  JETOUR: ['X70', 'X70 PLUS', 'X90', 'DASHING'],
  ISUZU: ['D-MAX', 'MU-X', 'NPR', 'NQR', 'NLS', 'ELF', 'FORWARD'],
  SSANGYONG: ['KORANDO', 'ACTYON', 'REXTON', 'MUSSO', 'TIVOLI'],
  DAIHATSU: ['TERIOS', 'SIRION', 'BOON'],
  LEXUS: ['NX', 'RX', 'GX', 'LX', 'IS', 'ES', 'LS'],

  // ── CAMIONES MEDIANOS / PESADOS ──────────────────────────────────────────
  // Nota: HINO e INTERNATIONAL los manejan seeds de detalle (hino-300-dutro, international-7400-workstar)
  KENWORTH: [
    'T300',
    'T370',
    'T440',
    'T480',
    'T680',
    'T800',
    'T880',
    'W900',
    'T170',
    'T270',
    'C500',
    'K100',
  ],
  FREIGHTLINER: [
    'M2 106',
    'M2 112',
    'CASCADIA',
    'COLUMBIA',
    'CENTURY',
    'CLASSIC',
    'CORONADO',
    '114SD',
    '122SD',
  ],
  SCANIA: [
    'P SERIES',
    'G SERIES',
    'R SERIES',
    'S SERIES',
    'L SERIES',
    'P310',
    'P360',
    'G410',
    'R450',
    'R500',
    'S500',
    'S650',
  ],
  IVECO: [
    'DAILY',
    'EUROCARGO',
    'TRAKKER',
    'STRALIS',
    'HIWAY',
    'S-WAY',
    'EUROTRAKKER',
  ],
  MACK: ['GRANITE', 'ANTHEM', 'PINNACLE', 'TITAN', 'CH SERIES', 'DM SERIES'],
  PETERBILT: ['389', '388', '386', '579', '567', '548', '520', '337', '348'],
  FOTON: ['AUMARK', 'AUMAN', 'EST-M', 'BJ1030', 'BJ1163'],
  FAW: ['J6P', 'J7', 'CA1083', 'CA1163', 'JIEFANG'],
  SINOTRUK: ['HOWO', 'HOWO-T7H', 'HOWO A7', 'SITRAK'],
  SHACMAN: ['X3000', 'X5000', 'H3000', 'F3000', 'M3000'],
  NAVISTAR: ['9800I', 'PROSTAR'],
  'UD TRUCKS': ['QUESTER', 'CRONER', 'CONDOR'],

  // ── MICROBUSES / BUSES ────────────────────────────────────────────────────
  YUTONG: ['ZK6116H', 'ZK6126H', 'ZK6852H', 'ZK6729D', 'ZK6938H', 'E12'],
  'KING LONG': ['XMQ6900', 'XMQ6127', 'XMQ6113'],
  MARCOPOLO: ['VIALE BRT', 'TORINO GDD', 'PARADISO GLD', 'AUDACE'],

  // ── MOTOCICLETAS ──────────────────────────────────────────────────────────
  YAMAHA: [
    'YBR125',
    'FZ25',
    'FZ-S',
    'MT-03',
    'MT-07',
    'XTZ125',
    'XTZ150',
    'NMAX125',
    'XMAX300',
    'RX115',
    'CRYPTON110',
    'WR155',
    'BWIS115',
    'SZRR',
    'YZF-R3',
  ],
  'AUTECO BAJAJ': [
    'BOXER CT100',
    'BOXER BM150',
    'PULSAR NS125',
    'PULSAR NS160',
    'PULSAR NS200',
    'PULSAR RS200',
    'PULSAR N250',
    'DOMINAR 400',
    'CT100',
    'PLATINA 110',
  ],
  AKT: [
    'AK125',
    'AK150',
    'TTR200',
    'DYNAMIC 125',
    'NITRO150',
    'EVO200R',
    'NAKED200',
    'CR5 125',
  ],
  TVS: [
    'APACHE RTR160',
    'APACHE RTR200 4V',
    'NTORQ125',
    'STAR CITY PLUS',
    'RADEON110',
    'JUPITER125',
    'RONIN225',
  ],
  HERO: [
    'SPLENDOR PLUS',
    'PASSION PRO',
    'GLAMOUR',
    'HUNK150',
    'XPULSE200',
    'DESTINI125',
    'MAESTRO EDGE125',
  ],
  KAWASAKI: [
    'Z400',
    'Z650',
    'Z900',
    'NINJA 400',
    'NINJA 650',
    'NINJA 1000',
    'VERSYS 650',
    'KLX150',
    'KLX300',
  ],
  KTM: [
    'DUKE 200',
    'DUKE 390',
    'RC 200',
    'RC 390',
    'ADVENTURE 390',
    'EXC 250',
    'EXC-F 350',
  ],
  'ROYAL ENFIELD': [
    'BULLET 350',
    'CLASSIC 350',
    'METEOR 350',
    'HIMALAYAN',
    'HUNTER 350',
    'SCRAM 411',
    'INTERCEPTOR 650',
    'CONTINENTAL GT 650',
  ],
  'HARLEY DAVIDSON': [
    'SPORTSTER',
    'STREET GLIDE',
    'ROAD GLIDE',
    'ROAD KING',
    'FAT BOY',
    'SOFTAIL',
    'IRON 883',
    'STREET 750',
  ],
  BAJAJ: [
    'BOXER CT100',
    'PULSAR 135',
    'PULSAR 150',
    'PULSAR 180',
    'PLATINA 110',
    'DISCOVER 125',
  ],
  'HONDA (MOTOS)': [
    'CB150',
    'CB190',
    'CB300',
    'CB650',
    'XR150L',
    'XR190L',
    'XR650L',
    'CBF150',
    'WAVE110',
    'BROSS150',
    'TITAN160',
    'CG150',
    'NXR BROS',
    'PCX150',
    'ADV150',
  ],

  // ── MAQUINARIA PESADA ────────────────────────────────────────────────────
  CATERPILLAR: [
    '320',
    '323',
    '330',
    '336',
    '345',
    '950',
    '966',
    '972',
    '980',
    'D6',
    'D7',
    'D8',
    'D10',
    '12M',
    '14M',
    '16M',
    '740',
    '745',
    '773',
    '777',
    '785',
    '789',
    '416',
    '420',
    '432',
    '434',
    '444',
  ],
  KOMATSU: [
    'PC200',
    'PC210',
    'PC300',
    'PC350',
    'PC450',
    'WA250',
    'WA380',
    'WA470',
    'GD555',
    'GD655',
    'GD675',
    'D61',
    'D65',
    'D85',
    'HM300',
    'HM400',
  ],
  'JOHN DEERE': [
    '5075E',
    '5085E',
    '6110M',
    '6120M',
    '6130M',
    '544K',
    '624K',
    '644K',
    '310L',
    '410L',
    '710L',
    '670G',
    '770G',
    '870G',
    '333G',
    '323G',
  ],
  CASE: [
    '580N',
    '590SN',
    '695ST',
    '621G',
    '721G',
    '821G',
    '921G',
    'CX130D',
    'CX210D',
    'CX300D',
  ],
  'NEW HOLLAND': [
    'TL75',
    'TL85',
    'TM150',
    'W80C',
    'W110C',
    'W130C',
    'E115C',
    'E145C',
    'E215C',
  ],
  BOBCAT: [
    'S570',
    'S650',
    'S740',
    'T750',
    'T870',
    'E26',
    'E35',
    'E50',
    'E60',
    'E85',
    'A770',
  ],
  JCB: [
    '3CX',
    '4CX',
    '5CX',
    '457',
    '457 PLUS',
    'JS130',
    'JS210',
    'JS330',
    '508-70',
    '510-56',
    '525-60',
  ],
  XCMG: [
    'LW300FN',
    'LW500FN',
    'LW600KN',
    'XS202',
    'XS223',
    'XS2303',
    'XE150D',
    'XE215C',
    'XE370CA',
  ],
  HITACHI: ['ZX130', 'ZX200', 'ZX210', 'ZX350', 'ZX490', 'EX300', 'EX400'],
};

// Marcas sin líneas cargadas (solo la marca en el catálogo global)
const BRANDS_ONLY: string[] = [
  'ACURA',
  'ALFA ROMEO',
  'APRILIA',
  'ARO',
  'ASIA',
  'AVIA',
  'BAIC',
  'BEDFORD',
  'BEIJING',
  'BENELLI',
  'BENTLEY',
  'BLUE BIRD',
  'BRP',
  'BUICK',
  'CADILLAC',
  'CFMOTO',
  'CHANGAN',
  'CHRYSLER',
  'CLARK',
  'CUPRA',
  'DACIA',
  'DAF',
  'DATSUN',
  'DAEWOO',
  'DAELIM',
  'DFSK',
  'DINLI',
  'DONG FENG',
  'DONGFENG',
  'DS',
  'DUCATI',
  'FERRARI',
  'FUSO',
  'GAZ',
  'GMC',
  'GOLDEN DRAGON',
  'GONOW',
  'HAFEI',
  'HAIMA',
  'HISUN',
  'HUSQVARNA',
  'HYOSUNG',
  'JAC (MOTOS)',
  'JAGUAR',
  'JAWA',
  'JINCHENG',
  'JMC',
  'KAMAZ',
  'KARRY',
  'KEEWAY',
  'KIMCO',
  'KOBELCO',
  'KUBOTA',
  'KYMCO',
  'LADA',
  'LIFAN',
  'LINCOLN',
  'LIUGONG',
  'MAHINDRA',
  'MASERATI',
  'MINI',
  'MV AGUSTA',
  'NAVECO',
  'NIU',
  'NOVA',
  'OPEL',
  'PIAGGIO',
  'POLARIS',
  'PONTIAC',
  'PORSCHE',
  'QINGQI',
  'RAM TRUCKS',
  'SAAB',
  'SAIC WULING',
  'SAMSUNG',
  'SCOOTER',
  'SDLG',
  'SEAT',
  'SEGWAY',
  'SHINERAY',
  'SKODA',
  'SUNLONG',
  'SUNWIN',
  'SUPER SOCO',
  'SYM',
  'TATA',
  'THOMAS BUILT BUSES',
  'UAZ',
  'UM',
  'VENTO',
  'VESPA',
  'VICTORY',
  'WILLYS',
  'WULING',
  'YADEA',
  'YUEJIN',
  'YUCHAI',
  'ZASTAVA',
  'ZONGSHEN',
  'ZOTYE',
];

export async function seedVehicleCatalog(prisma: PrismaClient): Promise<void> {
  console.log(
    '\n   [CATALOG] Seeding marcas y líneas de vehículos globales...'
  );

  let brandCount = 0;
  let lineCount = 0;

  async function findOrCreateBrand(name: string) {
    let brand = await prisma.vehicleBrand.findFirst({
      where: { name, tenantId: null },
    });
    if (!brand) {
      brand = await prisma.vehicleBrand.create({
        data: { name, isGlobal: true, tenantId: null },
      });
      brandCount++;
    }
    return brand;
  }

  // Marcas con líneas
  for (const [brandName, lines] of Object.entries(CATALOG)) {
    const brand = await findOrCreateBrand(brandName);

    for (const lineName of lines) {
      const existing = await prisma.vehicleLine.findFirst({
        where: { brandId: brand.id, name: lineName, tenantId: null },
      });
      if (!existing) {
        await prisma.vehicleLine.create({
          data: {
            name: lineName,
            isGlobal: true,
            tenantId: null,
            brandId: brand.id,
          },
        });
        lineCount++;
      }
    }
  }

  // Marcas sin líneas
  for (const brandName of BRANDS_ONLY) {
    await findOrCreateBrand(brandName);
  }

  console.log(
    `   [CATALOG] ✓ ${brandCount} marcas, ${lineCount} líneas globales cargadas.\n`
  );
}
